#ifndef T2_H_
#define T2_H_

#include <stdio.h>

#include "types.h"
#include "photon.h"
#include "options.h"

typedef struct {
	uint32_t channel;
	int64_t time;
} t2_t;

typedef int (*t2_next_t)(FILE *, t2_t *);
typedef int (*t2_print_t)(FILE *, t2_t const *);

int t2_fread(FILE *stream_in, t2_t *t2);
int t2_fscanf(FILE *stream_in, t2_t *t2);
int t2_fprintf(FILE *stream_out, t2_t const *t2);
int t2_fwrite(FILE *stream_out, t2_t const *t2);
#define T2_NEXT(x) ( x ? t2_fread : t2_fscanf );
#define T2_PRINT(x) ( x ? t2_fwrite : t2_fprintf );

int t2_compare(void const *a, void const *b);
int t2_echo(FILE *stream_in, FILE *stream_out, int binary_in, int binary_out);

/* Here be legacy code, which will be going away/being modified soon. */
typedef struct {
	int32_t length;
	int64_t left_index;
	int64_t right_index;
	t2_t *queue;
} t2_queue_t;

int next_t2(FILE *stream_in, t2_t *record, options_t *options);
void print_t2(FILE *stream_out, t2_t *record, int print_newline,
		options_t *options);

t2_queue_t *allocate_t2_queue(int queue_length);
void free_t2_queue(t2_queue_t **queue);
int t2_queue_full(t2_queue_t *queue);
int t2_queue_pop(t2_queue_t *queue, t2_t *record);
int t2_queue_push(t2_queue_t *queue, t2_t *record);
int t2_queue_front(t2_queue_t *queue, t2_t *record);
int t2_queue_back(t2_queue_t *queue, t2_t *record);
int t2_queue_index(t2_queue_t *queue, t2_t *record, int index);
int64_t t2_queue_size(t2_queue_t *queue);
void t2_queue_sort(t2_queue_t *queue);
void yield_t2_queue(FILE *stream_out, t2_queue_t *queue, options_t *options);

/* The windowed stream represents a series of streams which are composed of
 * photons in some time window. For example, an intensity stream can be 
 * generated by counting all photons in 50ms bins, so we want to be able
 * to produce all photons in consecutive 50ms windows.
 */
typedef struct {
	window_t limits;
	int64_t width;
	int set_time_limit;
	int64_t time_limit;
} t2_window_t;

typedef struct {
	t2_t current_photon;
	int yielded_photon;
	t2_window_t window;
	FILE *stream_in;
} t2_windowed_stream_t;

void init_t2_window(t2_window_t *window, 
		int64_t start_time, options_t *options);
void next_t2_window(t2_window_t *window);
int init_t2_windowed_stream(t2_windowed_stream_t *stream,
		FILE *stream_in, options_t *options);
int next_t2_windowed(t2_windowed_stream_t *stream, t2_t *record,
		options_t *options);

#endif
